apiVersion: batch/v1
kind: Job 
metadata: 
 name: py 
spec:
 template:
  metadata:
   name: py
  spec:
   containers:
   - name: py
     image: python
     command: ["python", "SUCCESS"]
     restartPolicy: Never
  