apiVersion: v1
kind: ReplicationController 
metadata:
 name: my-rcsvc
spec:
 replicas: 3
 selector:
    app: mynginx
 
 template:
  metadata:
    labels:
     app: mynginx
  spec:
   containers:
    - name: my-nginx-container
      image: nginx
      ports:
       - containerPort: 80
