
apiVersion: v1
kind: ReplicationController
metadata: 
 name: my-rc
spec:
 replicas: 3
 selector:
  app: myapp


template:
 metadata:
  name: myapp
  labels:
   name: myapp

 spec:
  containers:
   - name: mynginx
     image: nginx
     ports:
     - containerPort: 80 


